// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountMessage.proto

package org.mmo.message;

public interface HeartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.HeartRequest)
    com.google.protobuf.MessageOrBuilder {
}
