// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountMessage.proto

package org.mmo.message;

public interface HeartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.HeartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *服务器时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();
}
