// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public interface HttpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.HttpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *路径
   * </pre>
   *
   * <code>string path = 1;</code>
   * @return The path.
   */
  String getPath();
  /**
   * <pre>
   *路径
   * </pre>
   *
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   *唯一标识id
   * </pre>
   *
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *json字符串参数
   * </pre>
   *
   * <code>string jsonParam = 3;</code>
   * @return The jsonParam.
   */
  String getJsonParam();
  /**
   * <pre>
   *json字符串参数
   * </pre>
   *
   * <code>string jsonParam = 3;</code>
   * @return The bytes for jsonParam.
   */
  com.google.protobuf.ByteString
      getJsonParamBytes();
}
