// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package org.mmo.message;

public interface ItemListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ItemListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>repeated .ProtoMessage.ItemInfo item = 1;</code>
   */
  java.util.List<org.mmo.message.ItemInfo> 
      getItemList();
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>repeated .ProtoMessage.ItemInfo item = 1;</code>
   */
  org.mmo.message.ItemInfo getItem(int index);
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>repeated .ProtoMessage.ItemInfo item = 1;</code>
   */
  int getItemCount();
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>repeated .ProtoMessage.ItemInfo item = 1;</code>
   */
  java.util.List<? extends org.mmo.message.ItemInfoOrBuilder> 
      getItemOrBuilderList();
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>repeated .ProtoMessage.ItemInfo item = 1;</code>
   */
  org.mmo.message.ItemInfoOrBuilder getItemOrBuilder(
      int index);
}
