// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package org.mmo.message;

public interface ItemListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ItemListRequest)
    com.google.protobuf.MessageOrBuilder {
}
