// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package org.mmo.message;

public final class ItemMessage {
  private ItemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ItemListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ItemListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ItemListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ItemListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ItemInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ItemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ItemMessage.proto\022\014ProtoMessage\"\021\n\017Ite" +
      "mListRequest\"8\n\020ItemListResponse\022$\n\004item" +
      "\030\001 \003(\0132\026.ProtoMessage.ItemInfo\"7\n\010ItemIn" +
      "fo\022\n\n\002id\030\001 \001(\003\022\020\n\010configId\030\002 \001(\005\022\r\n\005coun" +
      "t\030\003 \001(\003B)\n\017org.mmo.messageB\013ItemMessageP" +
      "\001Z\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoMessage_ItemListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_ItemListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ItemListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ProtoMessage_ItemListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoMessage_ItemListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ItemListResponse_descriptor,
        new java.lang.String[] { "Item", });
    internal_static_ProtoMessage_ItemInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoMessage_ItemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ItemInfo_descriptor,
        new java.lang.String[] { "Id", "ConfigId", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
