// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public interface LoadScriptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.LoadScriptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *加载信息
   * </pre>
   *
   * <code>string info = 1;</code>
   * @return The info.
   */
  String getInfo();
  /**
   * <pre>
   *加载信息
   * </pre>
   *
   * <code>string info = 1;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
