// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public interface LoadScriptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.LoadScriptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *加载路径，null全加载
   * </pre>
   *
   * <code>string path = 1;</code>
   * @return The path.
   */
  String getPath();
  /**
   * <pre>
   *加载路径，null全加载
   * </pre>
   *
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
