// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountMessage.proto

package org.mmo.message;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *用户id
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
