// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountMessage.proto

package org.mmo.message;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string account = 1;</code>
   * @return The account.
   */
  String getAccount();
  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string account = 1;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <pre>
   *密码
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <pre>
   *密码
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
