// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MIDMessage.proto

package org.mmo.message;

public final class MIDMessage {
  private MIDMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ProtoMessage.MID}
   */
  public enum MID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>None = 0;</code>
     */
    None(0),
    /**
     * <pre>
     *服务器注册
     * </pre>
     *
     * <code>ServerRegisterUpdateReq = 1;</code>
     */
    ServerRegisterUpdateReq(1),
    /**
     * <pre>
     *服务器注册
     * </pre>
     *
     * <code>ServerRegisterUpdateRes = 2;</code>
     */
    ServerRegisterUpdateRes(2),
    /**
     * <pre>
     *账号模块100000-100100
     * </pre>
     *
     * <code>LoginReq = 100000;</code>
     */
    LoginReq(100000),
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LoginRes = 100001;</code>
     */
    LoginRes(100001),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HeartReq = 100002;</code>
     */
    HeartReq(100002),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HeartRes = 100003;</code>
     */
    HeartRes(100003),
    /**
     * <pre>
     *角色模块100200-100300
     * </pre>
     *
     * <code>PlayerInfoReq = 100200;</code>
     */
    PlayerInfoReq(100200),
    /**
     * <pre>
     *角色信息
     * </pre>
     *
     * <code>PlayerInfoRes = 100201;</code>
     */
    PlayerInfoRes(100201),
    /**
     * <pre>
     *角色模块100300-100400
     * </pre>
     *
     * <code>ItemListReq = 100300;</code>
     */
    ItemListReq(100300),
    /**
     * <pre>
     *道具列表
     * </pre>
     *
     * <code>ItemListRes = 100301;</code>
     */
    ItemListRes(100301),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>None = 0;</code>
     */
    public static final int None_VALUE = 0;
    /**
     * <pre>
     *服务器注册
     * </pre>
     *
     * <code>ServerRegisterUpdateReq = 1;</code>
     */
    public static final int ServerRegisterUpdateReq_VALUE = 1;
    /**
     * <pre>
     *服务器注册
     * </pre>
     *
     * <code>ServerRegisterUpdateRes = 2;</code>
     */
    public static final int ServerRegisterUpdateRes_VALUE = 2;
    /**
     * <pre>
     *账号模块100000-100100
     * </pre>
     *
     * <code>LoginReq = 100000;</code>
     */
    public static final int LoginReq_VALUE = 100000;
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LoginRes = 100001;</code>
     */
    public static final int LoginRes_VALUE = 100001;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HeartReq = 100002;</code>
     */
    public static final int HeartReq_VALUE = 100002;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HeartRes = 100003;</code>
     */
    public static final int HeartRes_VALUE = 100003;
    /**
     * <pre>
     *角色模块100200-100300
     * </pre>
     *
     * <code>PlayerInfoReq = 100200;</code>
     */
    public static final int PlayerInfoReq_VALUE = 100200;
    /**
     * <pre>
     *角色信息
     * </pre>
     *
     * <code>PlayerInfoRes = 100201;</code>
     */
    public static final int PlayerInfoRes_VALUE = 100201;
    /**
     * <pre>
     *角色模块100300-100400
     * </pre>
     *
     * <code>ItemListReq = 100300;</code>
     */
    public static final int ItemListReq_VALUE = 100300;
    /**
     * <pre>
     *道具列表
     * </pre>
     *
     * <code>ItemListRes = 100301;</code>
     */
    public static final int ItemListRes_VALUE = 100301;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MID valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MID forNumber(int value) {
      switch (value) {
        case 0: return None;
        case 1: return ServerRegisterUpdateReq;
        case 2: return ServerRegisterUpdateRes;
        case 100000: return LoginReq;
        case 100001: return LoginRes;
        case 100002: return HeartReq;
        case 100003: return HeartRes;
        case 100200: return PlayerInfoReq;
        case 100201: return PlayerInfoRes;
        case 100300: return ItemListReq;
        case 100301: return ItemListRes;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MID>() {
            public MID findValueByNumber(int number) {
              return MID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.mmo.message.MIDMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MID[] VALUES = values();

    public static MID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoMessage.MID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MIDMessage.proto\022\014ProtoMessage*\331\001\n\003MID" +
      "\022\010\n\004None\020\000\022\033\n\027ServerRegisterUpdateReq\020\001\022" +
      "\033\n\027ServerRegisterUpdateRes\020\002\022\016\n\010LoginReq" +
      "\020\240\215\006\022\016\n\010LoginRes\020\241\215\006\022\016\n\010HeartReq\020\242\215\006\022\016\n\010" +
      "HeartRes\020\243\215\006\022\023\n\rPlayerInfoReq\020\350\216\006\022\023\n\rPla" +
      "yerInfoRes\020\351\216\006\022\021\n\013ItemListReq\020\314\217\006\022\021\n\013Ite" +
      "mListRes\020\315\217\006B\032\n\017org.mmo.messageZ\007message" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
