// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerMessage.proto

package org.mmo.message;

public final class PlayerMessage {
  private PlayerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_PlayerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_PlayerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_PlayerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_PlayerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_PlayerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_PlayerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023PlayerMessage.proto\022\014ProtoMessage\"#\n\021P" +
      "layerInfoRequest\022\016\n\006userId\030\001 \001(\003\"N\n\022Play" +
      "erInfoResponse\022\016\n\006userId\030\001 \001(\003\022(\n\006player" +
      "\030\002 \001(\0132\030.ProtoMessage.PlayerInfo\"H\n\nPlay" +
      "erInfo\022\020\n\010playerId\030\001 \001(\003\022\r\n\005level\030\002 \001(\005\022" +
      "\013\n\003exp\030\003 \001(\003\022\014\n\004name\030\004 \001(\tB+\n\017org.mmo.me" +
      "ssageB\rPlayerMessageP\001Z\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoMessage_PlayerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_PlayerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_PlayerInfoRequest_descriptor,
        new String[] { "UserId", });
    internal_static_ProtoMessage_PlayerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoMessage_PlayerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_PlayerInfoResponse_descriptor,
        new String[] { "UserId", "Player", });
    internal_static_ProtoMessage_PlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoMessage_PlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_PlayerInfo_descriptor,
        new String[] { "PlayerId", "Level", "Exp", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
