// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerMessage.proto

package org.mmo.message;

public interface PlayerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.PlayerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *玩家id
   * </pre>
   *
   * <code>int64 playerId = 1;</code>
   * @return The playerId.
   */
  long getPlayerId();

  /**
   * <pre>
   *等级
   * </pre>
   *
   * <code>int32 level = 2;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   *经验
   * </pre>
   *
   * <code>int64 exp = 3;</code>
   * @return The exp.
   */
  long getExp();

  /**
   * <pre>
   *昵称
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   *昵称
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
