// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerMessage.proto

package org.mmo.message;

/**
 * <pre>
 *玩家信息请求
 * </pre>
 *
 * Protobuf type {@code ProtoMessage.PlayerInfoResponse}
 */
public  final class PlayerInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoMessage.PlayerInfoResponse)
    PlayerInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerInfoResponse.newBuilder() to construct.
  private PlayerInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerInfoResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerInfoResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PlayerInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 18: {
            org.mmo.message.PlayerInfo.Builder subBuilder = null;
            if (player_ != null) {
              subBuilder = player_.toBuilder();
            }
            player_ = input.readMessage(org.mmo.message.PlayerInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(player_);
              player_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mmo.message.PlayerMessage.internal_static_ProtoMessage_PlayerInfoResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mmo.message.PlayerMessage.internal_static_ProtoMessage_PlayerInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mmo.message.PlayerInfoResponse.class, org.mmo.message.PlayerInfoResponse.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <pre>
   *用户id
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  public long getUserId() {
    return userId_;
  }

  public static final int PLAYER_FIELD_NUMBER = 2;
  private org.mmo.message.PlayerInfo player_;
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>.ProtoMessage.PlayerInfo player = 2;</code>
   * @return Whether the player field is set.
   */
  public boolean hasPlayer() {
    return player_ != null;
  }
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>.ProtoMessage.PlayerInfo player = 2;</code>
   * @return The player.
   */
  public org.mmo.message.PlayerInfo getPlayer() {
    return player_ == null ? org.mmo.message.PlayerInfo.getDefaultInstance() : player_;
  }
  /**
   * <pre>
   *玩家信息
   * </pre>
   *
   * <code>.ProtoMessage.PlayerInfo player = 2;</code>
   */
  public org.mmo.message.PlayerInfoOrBuilder getPlayerOrBuilder() {
    return getPlayer();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (player_ != null) {
      output.writeMessage(2, getPlayer());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (player_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPlayer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mmo.message.PlayerInfoResponse)) {
      return super.equals(obj);
    }
    org.mmo.message.PlayerInfoResponse other = (org.mmo.message.PlayerInfoResponse) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (hasPlayer() != other.hasPlayer()) return false;
    if (hasPlayer()) {
      if (!getPlayer()
          .equals(other.getPlayer())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    if (hasPlayer()) {
      hash = (37 * hash) + PLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mmo.message.PlayerInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mmo.message.PlayerInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mmo.message.PlayerInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mmo.message.PlayerInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mmo.message.PlayerInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *玩家信息请求
   * </pre>
   *
   * Protobuf type {@code ProtoMessage.PlayerInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoMessage.PlayerInfoResponse)
      org.mmo.message.PlayerInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mmo.message.PlayerMessage.internal_static_ProtoMessage_PlayerInfoResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mmo.message.PlayerMessage.internal_static_ProtoMessage_PlayerInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mmo.message.PlayerInfoResponse.class, org.mmo.message.PlayerInfoResponse.Builder.class);
    }

    // Construct using org.mmo.message.PlayerInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      if (playerBuilder_ == null) {
        player_ = null;
      } else {
        player_ = null;
        playerBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mmo.message.PlayerMessage.internal_static_ProtoMessage_PlayerInfoResponse_descriptor;
    }

    @Override
    public org.mmo.message.PlayerInfoResponse getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public org.mmo.message.PlayerInfoResponse build() {
      org.mmo.message.PlayerInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.mmo.message.PlayerInfoResponse buildPartial() {
      org.mmo.message.PlayerInfoResponse result = new org.mmo.message.PlayerInfoResponse(this);
      result.userId_ = userId_;
      if (playerBuilder_ == null) {
        result.player_ = player_;
      } else {
        result.player_ = playerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mmo.message.PlayerInfoResponse) {
        return mergeFrom((org.mmo.message.PlayerInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mmo.message.PlayerInfoResponse other) {
      if (other == getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.hasPlayer()) {
        mergePlayer(other.getPlayer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mmo.message.PlayerInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mmo.message.PlayerInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private org.mmo.message.PlayerInfo player_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mmo.message.PlayerInfo, org.mmo.message.PlayerInfo.Builder, org.mmo.message.PlayerInfoOrBuilder> playerBuilder_;
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     * @return Whether the player field is set.
     */
    public boolean hasPlayer() {
      return playerBuilder_ != null || player_ != null;
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     * @return The player.
     */
    public org.mmo.message.PlayerInfo getPlayer() {
      if (playerBuilder_ == null) {
        return player_ == null ? org.mmo.message.PlayerInfo.getDefaultInstance() : player_;
      } else {
        return playerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public Builder setPlayer(org.mmo.message.PlayerInfo value) {
      if (playerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        player_ = value;
        onChanged();
      } else {
        playerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public Builder setPlayer(
        org.mmo.message.PlayerInfo.Builder builderForValue) {
      if (playerBuilder_ == null) {
        player_ = builderForValue.build();
        onChanged();
      } else {
        playerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public Builder mergePlayer(org.mmo.message.PlayerInfo value) {
      if (playerBuilder_ == null) {
        if (player_ != null) {
          player_ =
            org.mmo.message.PlayerInfo.newBuilder(player_).mergeFrom(value).buildPartial();
        } else {
          player_ = value;
        }
        onChanged();
      } else {
        playerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public Builder clearPlayer() {
      if (playerBuilder_ == null) {
        player_ = null;
        onChanged();
      } else {
        player_ = null;
        playerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public org.mmo.message.PlayerInfo.Builder getPlayerBuilder() {
      
      onChanged();
      return getPlayerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    public org.mmo.message.PlayerInfoOrBuilder getPlayerOrBuilder() {
      if (playerBuilder_ != null) {
        return playerBuilder_.getMessageOrBuilder();
      } else {
        return player_ == null ?
            org.mmo.message.PlayerInfo.getDefaultInstance() : player_;
      }
    }
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>.ProtoMessage.PlayerInfo player = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mmo.message.PlayerInfo, org.mmo.message.PlayerInfo.Builder, org.mmo.message.PlayerInfoOrBuilder> 
        getPlayerFieldBuilder() {
      if (playerBuilder_ == null) {
        playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mmo.message.PlayerInfo, org.mmo.message.PlayerInfo.Builder, org.mmo.message.PlayerInfoOrBuilder>(
                getPlayer(),
                getParentForChildren(),
                isClean());
        player_ = null;
      }
      return playerBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProtoMessage.PlayerInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:ProtoMessage.PlayerInfoResponse)
  private static final org.mmo.message.PlayerInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mmo.message.PlayerInfoResponse();
  }

  public static org.mmo.message.PlayerInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<PlayerInfoResponse>() {
    @Override
    public PlayerInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PlayerInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlayerInfoResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PlayerInfoResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public org.mmo.message.PlayerInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

