// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public final class ServerMessage {
  private ServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerRegisterUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerRegisterUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerRegisterUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerRegisterUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_LoadScriptRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_LoadScriptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_LoadScriptResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_LoadScriptResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_HttpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_HttpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_HttpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_HttpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerMessage.proto\022\014ProtoMessage\"!\n\021S" +
      "erverListRequest\022\014\n\004type\030\002 \001(\005\">\n\022Server" +
      "ListResponse\022(\n\006server\030\002 \003(\0132\030.ProtoMess" +
      "age.ServerInfo\"\222\002\n\nServerInfo\022\n\n\002id\030\001 \001(" +
      "\005\022\020\n\010belongID\030\002 \001(\005\022\n\n\002ip\030\003 \001(\t\022\014\n\004type\030" +
      "\004 \001(\005\022\014\n\004port\030\005 \001(\005\022\r\n\005state\030\006 \001(\005\022\017\n\007ve" +
      "rsion\030\007 \001(\t\022\017\n\007content\030\010 \001(\t\022\016\n\006online\030\013" +
      " \001(\005\022\024\n\014maxUserCount\030\014 \001(\005\022\020\n\010httpPort\030\r" +
      " \001(\005\022\020\n\010openTime\030\016 \001(\t\022\024\n\014maintainTime\030\017" +
      " \001(\t\022\014\n\004name\030\020 \001(\t\022\r\n\005wwwip\030\021 \001(\t\022\020\n\010gam" +
      "ePort\030\022 \001(\005\"K\n\033ServerRegisterUpdateReque" +
      "st\022,\n\nserverInfo\030\002 \001(\0132\030.ProtoMessage.Se" +
      "rverInfo\"\\\n\034ServerRegisterUpdateResponse" +
      "\022,\n\nserverInfo\030\001 \001(\0132\030.ProtoMessage.Serv" +
      "erInfo\022\016\n\006status\030\002 \001(\005\"!\n\021LoadScriptRequ" +
      "est\022\014\n\004path\030\001 \001(\t\"\"\n\022LoadScriptResponse\022" +
      "\014\n\004info\030\001 \001(\t\":\n\013HttpRequest\022\014\n\004path\030\001 \001" +
      "(\t\022\n\n\002id\030\002 \001(\003\022\021\n\tjsonParam\030\003 \001(\t\",\n\014Htt" +
      "pResponse\022\014\n\004code\030\002 \001(\005\022\016\n\006result\030\003 \001(\t2" +
      "\304\003\n\rServerService\022g\n\016ServerRegister\022).Pr" +
      "otoMessage.ServerRegisterUpdateRequest\032*" +
      ".ProtoMessage.ServerRegisterUpdateRespon" +
      "se\022e\n\014ServerUpdate\022).ProtoMessage.Server" +
      "RegisterUpdateRequest\032*.ProtoMessage.Ser" +
      "verRegisterUpdateResponse\022O\n\nServerList\022" +
      "\037.ProtoMessage.ServerListRequest\032 .Proto" +
      "Message.ServerListResponse\022O\n\nLoadScript" +
      "\022\037.ProtoMessage.LoadScriptRequest\032 .Prot" +
      "oMessage.LoadScriptResponse\022A\n\010httpPost\022" +
      "\031.ProtoMessage.HttpRequest\032\032.ProtoMessag" +
      "e.HttpResponseB+\n\017org.mmo.messageB\rServe" +
      "rMessageP\001Z\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoMessage_ServerListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_ServerListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerListRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_ProtoMessage_ServerListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoMessage_ServerListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerListResponse_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_ProtoMessage_ServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoMessage_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerInfo_descriptor,
        new java.lang.String[] { "Id", "BelongID", "Ip", "Type", "Port", "State", "Version", "Content", "Online", "MaxUserCount", "HttpPort", "OpenTime", "MaintainTime", "Name", "Wwwip", "GamePort", });
    internal_static_ProtoMessage_ServerRegisterUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProtoMessage_ServerRegisterUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerRegisterUpdateRequest_descriptor,
        new java.lang.String[] { "ServerInfo", });
    internal_static_ProtoMessage_ServerRegisterUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ProtoMessage_ServerRegisterUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerRegisterUpdateResponse_descriptor,
        new java.lang.String[] { "ServerInfo", "Status", });
    internal_static_ProtoMessage_LoadScriptRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ProtoMessage_LoadScriptRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_LoadScriptRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_ProtoMessage_LoadScriptResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ProtoMessage_LoadScriptResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_LoadScriptResponse_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_ProtoMessage_HttpRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ProtoMessage_HttpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_HttpRequest_descriptor,
        new java.lang.String[] { "Path", "Id", "JsonParam", });
    internal_static_ProtoMessage_HttpResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ProtoMessage_HttpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_HttpResponse_descriptor,
        new java.lang.String[] { "Code", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
