// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public interface ServerRegisterUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ServerRegisterUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProtoMessage.ServerInfo serverInfo = 2;</code>
   * @return Whether the serverInfo field is set.
   */
  boolean hasServerInfo();
  /**
   * <code>.ProtoMessage.ServerInfo serverInfo = 2;</code>
   * @return The serverInfo.
   */
  org.mmo.message.ServerInfo getServerInfo();
  /**
   * <code>.ProtoMessage.ServerInfo serverInfo = 2;</code>
   */
  org.mmo.message.ServerInfoOrBuilder getServerInfoOrBuilder();
}
