// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package org.mmo.message;

public interface ServerListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ServerListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *服务器类型
   * </pre>
   *
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();
}
