// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

public interface DisConnectCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.DisConnectCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   * @return Whether the errorCode field is set.
   */
  boolean hasErrorCode();
  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   * @return The errorCode.
   */
  org.pot.message.protocol.ErrorCode getErrorCode();
  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   */
  org.pot.message.protocol.ErrorCodeOrBuilder getErrorCodeOrBuilder();
}
