// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

/**
 * Protobuf type {@code ProtoMessage.DisConnectCode}
 */
public  final class DisConnectCode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoMessage.DisConnectCode)
    DisConnectCodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DisConnectCode.newBuilder() to construct.
  private DisConnectCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DisConnectCode() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DisConnectCode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DisConnectCode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.pot.message.protocol.ErrorCode.Builder subBuilder = null;
            if (errorCode_ != null) {
              subBuilder = errorCode_.toBuilder();
            }
            errorCode_ = input.readMessage(org.pot.message.protocol.ErrorCode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(errorCode_);
              errorCode_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.pot.message.protocol.ServerMessage.internal_static_ProtoMessage_DisConnectCode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.pot.message.protocol.ServerMessage.internal_static_ProtoMessage_DisConnectCode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.pot.message.protocol.DisConnectCode.class, org.pot.message.protocol.DisConnectCode.Builder.class);
  }

  public static final int ERRORCODE_FIELD_NUMBER = 1;
  private org.pot.message.protocol.ErrorCode errorCode_;
  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   * @return Whether the errorCode field is set.
   */
  public boolean hasErrorCode() {
    return errorCode_ != null;
  }
  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   * @return The errorCode.
   */
  public org.pot.message.protocol.ErrorCode getErrorCode() {
    return errorCode_ == null ? org.pot.message.protocol.ErrorCode.getDefaultInstance() : errorCode_;
  }
  /**
   * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
   */
  public org.pot.message.protocol.ErrorCodeOrBuilder getErrorCodeOrBuilder() {
    return getErrorCode();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errorCode_ != null) {
      output.writeMessage(1, getErrorCode());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorCode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErrorCode());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.pot.message.protocol.DisConnectCode)) {
      return super.equals(obj);
    }
    org.pot.message.protocol.DisConnectCode other = (org.pot.message.protocol.DisConnectCode) obj;

    if (hasErrorCode() != other.hasErrorCode()) return false;
    if (hasErrorCode()) {
      if (!getErrorCode()
          .equals(other.getErrorCode())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErrorCode()) {
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.pot.message.protocol.DisConnectCode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pot.message.protocol.DisConnectCode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.pot.message.protocol.DisConnectCode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pot.message.protocol.DisConnectCode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.pot.message.protocol.DisConnectCode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProtoMessage.DisConnectCode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoMessage.DisConnectCode)
      org.pot.message.protocol.DisConnectCodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pot.message.protocol.ServerMessage.internal_static_ProtoMessage_DisConnectCode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pot.message.protocol.ServerMessage.internal_static_ProtoMessage_DisConnectCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pot.message.protocol.DisConnectCode.class, org.pot.message.protocol.DisConnectCode.Builder.class);
    }

    // Construct using org.pot.message.protocol.DisConnectCode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (errorCodeBuilder_ == null) {
        errorCode_ = null;
      } else {
        errorCode_ = null;
        errorCodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.pot.message.protocol.ServerMessage.internal_static_ProtoMessage_DisConnectCode_descriptor;
    }

    @java.lang.Override
    public org.pot.message.protocol.DisConnectCode getDefaultInstanceForType() {
      return org.pot.message.protocol.DisConnectCode.getDefaultInstance();
    }

    @java.lang.Override
    public org.pot.message.protocol.DisConnectCode build() {
      org.pot.message.protocol.DisConnectCode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.pot.message.protocol.DisConnectCode buildPartial() {
      org.pot.message.protocol.DisConnectCode result = new org.pot.message.protocol.DisConnectCode(this);
      if (errorCodeBuilder_ == null) {
        result.errorCode_ = errorCode_;
      } else {
        result.errorCode_ = errorCodeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.pot.message.protocol.DisConnectCode) {
        return mergeFrom((org.pot.message.protocol.DisConnectCode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.pot.message.protocol.DisConnectCode other) {
      if (other == org.pot.message.protocol.DisConnectCode.getDefaultInstance()) return this;
      if (other.hasErrorCode()) {
        mergeErrorCode(other.getErrorCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.pot.message.protocol.DisConnectCode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.pot.message.protocol.DisConnectCode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.pot.message.protocol.ErrorCode errorCode_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.pot.message.protocol.ErrorCode, org.pot.message.protocol.ErrorCode.Builder, org.pot.message.protocol.ErrorCodeOrBuilder> errorCodeBuilder_;
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     * @return Whether the errorCode field is set.
     */
    public boolean hasErrorCode() {
      return errorCodeBuilder_ != null || errorCode_ != null;
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     * @return The errorCode.
     */
    public org.pot.message.protocol.ErrorCode getErrorCode() {
      if (errorCodeBuilder_ == null) {
        return errorCode_ == null ? org.pot.message.protocol.ErrorCode.getDefaultInstance() : errorCode_;
      } else {
        return errorCodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public Builder setErrorCode(org.pot.message.protocol.ErrorCode value) {
      if (errorCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        errorCode_ = value;
        onChanged();
      } else {
        errorCodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public Builder setErrorCode(
        org.pot.message.protocol.ErrorCode.Builder builderForValue) {
      if (errorCodeBuilder_ == null) {
        errorCode_ = builderForValue.build();
        onChanged();
      } else {
        errorCodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public Builder mergeErrorCode(org.pot.message.protocol.ErrorCode value) {
      if (errorCodeBuilder_ == null) {
        if (errorCode_ != null) {
          errorCode_ =
            org.pot.message.protocol.ErrorCode.newBuilder(errorCode_).mergeFrom(value).buildPartial();
        } else {
          errorCode_ = value;
        }
        onChanged();
      } else {
        errorCodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public Builder clearErrorCode() {
      if (errorCodeBuilder_ == null) {
        errorCode_ = null;
        onChanged();
      } else {
        errorCode_ = null;
        errorCodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public org.pot.message.protocol.ErrorCode.Builder getErrorCodeBuilder() {
      
      onChanged();
      return getErrorCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    public org.pot.message.protocol.ErrorCodeOrBuilder getErrorCodeOrBuilder() {
      if (errorCodeBuilder_ != null) {
        return errorCodeBuilder_.getMessageOrBuilder();
      } else {
        return errorCode_ == null ?
            org.pot.message.protocol.ErrorCode.getDefaultInstance() : errorCode_;
      }
    }
    /**
     * <code>.ProtoMessage.ErrorCode errorCode = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.pot.message.protocol.ErrorCode, org.pot.message.protocol.ErrorCode.Builder, org.pot.message.protocol.ErrorCodeOrBuilder> 
        getErrorCodeFieldBuilder() {
      if (errorCodeBuilder_ == null) {
        errorCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.pot.message.protocol.ErrorCode, org.pot.message.protocol.ErrorCode.Builder, org.pot.message.protocol.ErrorCodeOrBuilder>(
                getErrorCode(),
                getParentForChildren(),
                isClean());
        errorCode_ = null;
      }
      return errorCodeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProtoMessage.DisConnectCode)
  }

  // @@protoc_insertion_point(class_scope:ProtoMessage.DisConnectCode)
  private static final org.pot.message.protocol.DisConnectCode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.pot.message.protocol.DisConnectCode();
  }

  public static org.pot.message.protocol.DisConnectCode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DisConnectCode>
      PARSER = new com.google.protobuf.AbstractParser<DisConnectCode>() {
    @java.lang.Override
    public DisConnectCode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DisConnectCode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DisConnectCode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DisConnectCode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.pot.message.protocol.DisConnectCode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

