// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

public interface ErrorCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ErrorCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();
}
