// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

public interface ServerNetPongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ServerNetPong)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProtoMessage.ServerNetPong ping = 1;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.ProtoMessage.ServerNetPong ping = 1;</code>
   * @return The ping.
   */
  org.pot.message.protocol.ServerNetPong getPing();
  /**
   * <code>.ProtoMessage.ServerNetPong ping = 1;</code>
   */
  org.pot.message.protocol.ServerNetPongOrBuilder getPingOrBuilder();
}
