// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

public final class ServerMessage {
  private ServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerNetPing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerNetPing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ServerNetPong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ServerNetPong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_ErrorCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_ErrorCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_DisConnectCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_DisConnectCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_AckCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_AckCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessage_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoMessage_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\014ProtoMessage\"\035\n\rServerNe" +
      "tPing\022\014\n\004time\030\001 \001(\003\":\n\rServerNetPong\022)\n\004" +
      "ping\030\001 \001(\0132\033.ProtoMessage.ServerNetPing\"" +
      "\'\n\tErrorCode\022\014\n\004name\030\001 \001(\t\022\014\n\004code\030\002 \001(\005" +
      "\"<\n\016DisConnectCode\022*\n\terrorCode\030\001 \001(\0132\027." +
      "ProtoMessage.ErrorCode\"\027\n\007AckCode\022\014\n\004nam" +
      "e\030\001 \001(\t\"\024\n\004Ping\022\014\n\004time\030\001 \001(\003\"(\n\004Pong\022 \n" +
      "\004ping\030\001 \001(\0132\022.ProtoMessage.PingB4\n\030org.p" +
      "ot.message.protocolB\rServerMessageP\001Z\007me" +
      "ssageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoMessage_ServerNetPing_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_ServerNetPing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerNetPing_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_ProtoMessage_ServerNetPong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoMessage_ServerNetPong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ServerNetPong_descriptor,
        new java.lang.String[] { "Ping", });
    internal_static_ProtoMessage_ErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoMessage_ErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_ErrorCode_descriptor,
        new java.lang.String[] { "Name", "Code", });
    internal_static_ProtoMessage_DisConnectCode_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProtoMessage_DisConnectCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_DisConnectCode_descriptor,
        new java.lang.String[] { "ErrorCode", });
    internal_static_ProtoMessage_AckCode_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ProtoMessage_AckCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_AckCode_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_ProtoMessage_Ping_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ProtoMessage_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_Ping_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_ProtoMessage_Pong_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ProtoMessage_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoMessage_Pong_descriptor,
        new java.lang.String[] { "Ping", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
