// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.pot.message.protocol;

public interface ServerNetPingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoMessage.ServerNetPing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();
}
